baseURL = "http://example.org/"
languageCode = "en-us"
title = "My LMS Platform"
theme = "lms"

[params]
  description = "A modern learning management system"
  logo = "/images/logo.png"

[taxonomies]
  category = "categories"
  tag = "tags"
  difficulty = "difficulties"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Courses"
    url = "/courses/"
    weight = 2
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5
