name = "Hugo LMS Theme"
license = "MIT"
licenselink = "https://github.com/yourusername/hugo-lms-theme/blob/master/LICENSE"
description = "A modern Learning Management System theme for Hugo"
homepage = "https://github.com/yourusername/hugo-lms-theme"
tags = ["lms", "education", "courses", "learning"]
features = [
    "course-management",
    "video-player",
    "responsive",
    "tailwind",
    "alpine-js"
]
min_version = "0.80.0"

[author]
    name = "Your Name"
    homepage = "https://yourwebsite.com"
